kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      # soft limit----Min limit for the container
      requests:
        cpu: "100m"
        memory: "128Mi"
      # limits should be atleast or more than requests i.e hard limit---max limit 
      limits:
        cpu: "100m"
        memory: "128Mi"